services:
  model_converter:
    container_name: embeddings-model-converter
    build: 
      context: model_converter
    volumes:
      - ./fastapi/onnx_model:/app/data
    restart: "no"
    env_file:
      - .env

  chroma:
    build: 
      context: chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data:/chroma/chroma
    environment:
      - ALLOW_RESET=true
      - CHROMA_SERVER_AUTH_PROVIDER=chromadb.auth.disabled.DisabledAuthServerProvider
      - CHROMA_SERVER_AUTH_CREDENTIALS_PROVIDER=chromadb.auth.disabled.DisabledAuthServerProvider
      - IS_PERSISTENT=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  fastapi:
    build:
      context: fastapi
    ports:
      - "8001:8001"
    volumes:
      - ./fastapi/onnx_model:/app/onnx_model
    depends_on:
      chroma:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
      - CHROMA_API_ENDPOINT=http://chroma:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    env_file:
        - .env

        
volumes:
  chroma_data:
    name: embeddings-data